export const data = {
  status: 'success',
  totalResults: 1066,
  results: [
    {
      article_id: 'd630f4f2577a58a686529702781cd19e',
      title:
        'Producto aclamado del D1 bajó de precio: clientes hacen fila para adquirirlo',
      link: 'https://www.rcnradio.com/colombia/productos-aclamado-del-d1-bajo-de-precio-clientes-hacen-fila-para-adquirirlo',
      keywords: null,
      creator: ['vavila'],
      video_url: null,
      description:
        'Autor vavila Las Tiendas D1, reconocidas por ofrecer productos de calidad a precios accesibles, continúan ganando popularidad en Colombia. Desde su llegada, han logrado posicionarse como una opción preferida para las compras diarias del hogar.Según datos proporcionados por la propia compañía, actualmente cuentan con 2.000 tiendas en todo el territorio colombiano, abarcando el 87% del país, distribuidas en 28 departamentos y 450 municipios.Le puede interesar: D1 novedoso horno para hacer pizza: cuesta menos de $149.900Esta expansión consolida a D1 como una de las marcas con mayor presencia física en Colombia, acercando sus productos a un amplio espectro de consumidores.Aceite de Oliva Extra Virgen del D1 bajo de precioUno de los factores que ha contribuido a su crecimiento es la viralización de sus productos en redes sociales. Entre los artículos que destacan en este ámbito se encuentra el aceite de oliva extra virgen, el cual ha captado la atención de los usuarios por su versatilidad en la cocina y en rutinas de cuidado personal.Inicialmente, se había reportado que el precio de este producto superaba los 24.000 pesos, sin embargo, recientemente ha experimentado una reducción significativa, llegando a costar tan solo 21.900 pesos, con la posibilidad de que continúe disminuyendo en el futuro cercano.Lea también: Electrodomésticos del D1 por menos de 150.000: son buenos y baratosEl aceite de oliva ofrecido por D1 es de la reconocida marca española Castell De Ferro, disponible en una presentación de botella de 500 ml y clasificado como Extra Virgen, garantizando así su calidad y pureza.Para adquirir este producto, los clientes tienen la opción de visitar las tiendas físicas de D1 o realizar sus compras a través de la página web, con la conveniencia de recibir los productos en la comodidad de sus hogares.¿Cómo solicitar domicilio en D1?Una de las consultas más comunes entre los usuarios es cómo solicitar el servicio de entrega a domicilio en las tiendas D1. Según la información proporcionada en el sitio web del supermercado, aquellos interesados deben seguir los siguientes pasos:Ingresar a la página web de D1.Navegar por la página y agregar los productos deseados al carrito de compra.Completar los datos requeridos por el sistema al momento de seleccionar los productos.Una vez completado el formulario, el cliente quedará registrado en el sistema.Finalmente, el sistema calculará el valor total del pedido y ofrecerá diferentes opciones de pago para elegir.Con estos pasos simples y la amplia variedad de productos disponibles, Tiendas D1 continúa facilitando el acceso a productos de calidad a precios accesibles para los hogares colombianos, consolidándose como una opción confiable y conveniente en el mercado minorista del país.',
      content: 'ONLY AVAILABLE IN PAID PLANS',
      pubDate: '2024-05-15 20:22:27',
      image_url:
        'https://files.rcnradio.com/public/styles/image_834x569/public/2024-03/tiendasd1.jpg.webp?VersionId=gXIkLT_p8vUjy8YzOw1tvRE48q0LyyNM&itok=DRiY54lE',
      source_id: 'rcnradio',
      source_priority: 105846,
      source_url: 'https://www.rcnradio.com',
      source_icon: 'https://i.bytvi.com/domain_icons/rcnradio.png',
      language: 'spanish',
      country: ['colombia'],
      category: ['top'],
      ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
    },
    {
      article_id: '160152b8e980e18e33d58f221c5cb4bd',
      title: 'Egg Plont pizza l ఎగ్‌ప్లాంట్‌ పిజ్జా తయారీ విధానం',
      link: 'https://www.ntnews.com/cooking/eggplant-pizza-recipe-1586555',
      keywords: [
        'news',
        'జిందగీ',
        'వంటలు',
        'cooking',
        'egg plont pizza',
        'recipes',
      ],
      creator: ['chandra kanth'],
      video_url: null,
      description: 'ఎగ్‌ప్లాంట్‌ పిజ్జా తయారీ విధానం',
      content: 'ONLY AVAILABLE IN PAID PLANS',
      pubDate: '2024-05-15 20:15:39',
      image_url:
        'https://d2e1hu1ktur9ur.cloudfront.net/wp-content/uploads/2024/05/Egg-Plont-pizza-1024x576.jpg',
      source_id: 'ntnews_in',
      source_priority: 182041,
      source_url: 'https://www.ntnews.com',
      source_icon: 'https://i.bytvi.com/domain_icons/ntnews_in.png',
      language: 'telugu',
      country: ['india'],
      category: ['food'],
      ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
    },
    {
      article_id: '6ea6f346bf60fdf98eb4ca0fbf51aa78',
      title:
        '35 Times Customers Proved That They Are Unquestionably The Absolute Dumbest People On Planet Earth',
      link: 'https://news.knowledia.com/all/all/articles/35-times-customers-proved-that-they-are-unquestionably-the-absolute-e73e9c2b9feafb6b8850d1808ad2c1f1560084e2?source=rss',
      keywords: null,
      creator: null,
      video_url: null,
      description:
        "You haven't lived until a customer looks you dead in the eye and asks how big the 12 inch pizza is. - www.buzzfeed.com",
      content: 'ONLY AVAILABLE IN PAID PLANS',
      pubDate: '2024-05-15 20:08:56',
      image_url:
        'https://img.buzzfeed.com/buzzfeed-static/static/2024-04/30/18/tmp/68aca664cb66/tmp-name-5-1483-1714502484-0_dblbig.jpg?resize=1200:*',
      source_id: 'knowledia',
      source_priority: 167779,
      source_url: 'http://news.knowledia.com',
      source_icon: 'https://i.bytvi.com/domain_icons/knowledia.png',
      language: 'english',
      country: ['india'],
      category: ['top'],
      ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
    },
    {
      article_id: '3165bd0231e3d3b74f86c8413de056b3',
      title:
        '35 Times Customers Proved That They Are Unquestionably The Absolute Dumbest People On Planet Earth',
      link: 'https://news.knowledia.com/US/en/articles/35-times-customers-proved-that-they-are-unquestionably-the-absolute-e73e9c2b9feafb6b8850d1808ad2c1f1560084e2?source=rss',
      keywords: null,
      creator: null,
      video_url: null,
      description:
        "You haven't lived until a customer looks you dead in the eye and asks how big the 12 inch pizza is. - www.buzzfeed.com",
      content: 'ONLY AVAILABLE IN PAID PLANS',
      pubDate: '2024-05-15 20:08:56',
      image_url:
        'https://img.buzzfeed.com/buzzfeed-static/static/2024-04/30/18/tmp/68aca664cb66/tmp-name-5-1483-1714502484-0_dblbig.jpg?resize=1200:*',
      source_id: 'knowledia',
      source_priority: 167779,
      source_url: 'http://news.knowledia.com',
      source_icon: 'https://i.bytvi.com/domain_icons/knowledia.png',
      language: 'english',
      country: ['united states of america'],
      category: ['top'],
      ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
    },
    {
      article_id: 'ef7e7b466a1705c670d165489e6db8af',
      title:
        'Erneuter Erfolg auf internationaler Bühne: Deutschlands beste Pizzeria liegt in Bayern',
      link: 'https://www.merkur.de/bayern/nuernberg/erneuter-erfolg-auf-internationaler-buehne-deutschlands-beste-pizzeria-ist-in-fuerth-93073092.html',
      keywords: null,
      creator: ['Niklas Hecht'],
      video_url: null,
      description:
        'Die „Pizza Zulu“ aus Fürth hat es wieder unter die besten Pizzerien Europas geschafft. Der Schlüssel zum Erfolg: Original neapolitanische Rezepte und frische Zutaten aus Italien.',
      content: 'ONLY AVAILABLE IN PAID PLANS',
      pubDate: '2024-05-15 20:03:45',
      image_url:
        'https://www.merkur.de/assets/images/34/48/34048234-lean-pizza-margherita-with-cheese-arugula-tomato-sauce-on-white-plate-your-text-here-lean-pizza-margherita-with-2401.jpg',
      source_id: 'merkur',
      source_priority: 359509,
      source_url: 'https://www.merkur.de',
      source_icon: 'https://i.bytvi.com/domain_icons/merkur.png',
      language: 'german',
      country: ['germany'],
      category: ['top'],
      ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
    },
    {
      article_id: '549d5a1834b34351dacc14c8729f67f3',
      title: 'Guía para vivir el Rock Fundación al máximo',
      link: 'https://www.elsudcaliforniano.com.mx/local/municipios/guia-para-vivir-el-rock-fundacion-al-maximo-11923150.html',
      keywords: ['municipios'],
      creator: null,
      video_url: null,
      description:
        'El acceso será a partir de las 17:00 horas en Nicolás Bravo y Marcelo Rubio, la entrada es gratis',
      content: 'ONLY AVAILABLE IN PAID PLANS',
      pubDate: '2024-05-15 20:03:17',
      image_url: null,
      source_id: 'elsudcaliforniano_mx',
      source_priority: 1195158,
      source_url: 'https://www.elsudcaliforniano.com.mx',
      source_icon: 'https://i.bytvi.com/domain_icons/elsudcaliforniano_mx.png',
      language: 'spanish',
      country: ['mexico'],
      category: ['top'],
      ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
    },
    {
      article_id: '8e0a776c84edb8d20d5a5cfd39465b82',
      title:
        'Lista de ganadores del Burger Master 2024: ¿quedaron sus favoritos?',
      link: 'https://www.rcnradio.com/estilo-de-vida/lista-de-ganadores-del-burger-master-2024-quedaron-sus-favoritos',
      keywords: ['estilo de vida'],
      creator: ['evillanueva'],
      video_url: null,
      description:
        "Autor evillanueva Los siete día del Burguer Master terminaron con grandes cifras, pues se vendieron un total de 2,9 millones de hamburguesas a lo largo del festival, según destacó su creador Tulio Zuloaga, generando $67.000 millones. El evento, que impulsó la economía colombiana, ha destinado el 60% de lo recaudado en el festival al sector agrícola colombiano. Tras algunos días, Tulio decidió dar a conocer las hamburguesas que conquistaron el corazón y paladar de los colombianos, destacando la calidad de su preparaciones.Lea además: Haga una tabla de quesos económica con productos del D1 por $35.000Este año, más de medio millón de votos válidos se recibieron en todo el país a través de la app TULIO Recomienda, reflejando la participación activa de los amantes de las hamburguesas en la elección de sus favoritos. Con un total de 579.000 votos válidos, más de 100 críticos evaluaron las hamburguesas en diferentes restaurantes.Mejores hamburguesas en BogotáEn la Capital colombiana, el primer lugar se lo ganó Camachos, este local participo con la Tote, con una carne necar angus, chicharrón y meloso de pera artesanal.Entre el top cinco también están Longos, Jimmy Burguer & Pizza, Burguer Town y Burger Depot.Los mejores restaurantes en Medellín Mientras que en la capital antioqueña, fue Chum Burguer la que mandó la parada, seguida de Bramante, LF Burger, Squad y All Day Café.La hamburguesa Chummy, de Chum, cautivó el paladar con una mezcla de carme de res, queso americano y chicharrón, así como chips de arracacha. De interés: Prepare una sangría deliciosa en minutos por menos de $35.000Cali y sus mejores hamburguesasEl festival gastronómico llegó a tocar las puertas de la sucursal del cielo, dejando como victoriosa la hamburguesa de Gaón. 'Maca', una preparación con carne Angus, queso stracciatella y un toque de orégano, así como mermelada de tocineta y balsámico. A esta se le sumaron las hamburguesas de Pancho y Josefina, Frank's, Pampa Malbec y Qrico.Bucaramanga ya tiene sus hamburguesas favoritasEn Bucaramanga, para este 2024 la ganadora fue Luigi JR, con su Black Panther, con pan pretzel, cremoso de queso con pimentón rostizado y tomates confitados con fondue de queso mozzarella.Seguida de Camachos, Burguer San Miguel, Parceros y El Menor. Conozca toda la lista de ganadores del Burguer Master 2024",
      content: 'ONLY AVAILABLE IN PAID PLANS',
      pubDate: '2024-05-15 20:01:48',
      image_url:
        'https://www.rcnradio.com/s3/files/styles/image_834x569/public/2024-04/burgermaster.jpg.webp?itok=I0qTKsr_',
      source_id: 'rcnradio',
      source_priority: 105846,
      source_url: 'https://www.rcnradio.com',
      source_icon: 'https://i.bytvi.com/domain_icons/rcnradio.png',
      language: 'spanish',
      country: ['colombia'],
      category: ['top'],
      ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
    },
    {
      article_id: '5ea4c0470b253ca08e1fbd805b8a27c1',
      title:
        'All Your Most Pressing Health Questions About ‘Survivor,’ Asked and Answered',
      link: 'https://www.self.com/story/survivor-contestants-answer-health-questions',
      keywords: ['life / entertainment', 'health'],
      creator: ['Amy Rose Spiegel'],
      video_url: null,
      description:
        'Do contestants have access to tampons? Can they take Adderall? And do they get awful hangovers after the Merge Feast?',
      content: 'ONLY AVAILABLE IN PAID PLANS',
      pubDate: '2024-05-15 20:00:13',
      image_url:
        'https://media.self.com/photos/6644ce273803e2d941f47a95/master/pass/GettyImages-1240406709.jpg',
      source_id: 'self',
      source_priority: 2129,
      source_url: 'https://www.self.com',
      source_icon: null,
      language: 'english',
      country: ['united states of america'],
      category: ['top'],
      ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
    },
    {
      article_id: '419e1ebeffa3ef307f05afd62cc32210',
      title: 'Cuisine – Gentle autumn stews',
      link: 'https://www.localmatters.co.nz/opinion/cuisine-gentle-autumn-stews/',
      keywords: ['health & lifestyle'],
      creator: ['Lauraine Jacobs'],
      video_url: null,
      description:
        'The thrill of a gentle stew simmering away on the stovetop, with sweet and savoury aromas wafting around the kitchen, is one of the joys...',
      content: 'ONLY AVAILABLE IN PAID PLANS',
      pubDate: '2024-05-15 20:00:00',
      image_url:
        'https://i0.wp.com/www.localmatters.co.nz/wp-content/uploads/2024/05/13-5-24_Cuisine.jpg?fit=1024%2C640=1',
      source_id: 'localmatters',
      source_priority: 2193151,
      source_url: 'https://www.localmatters.co.nz',
      source_icon: 'https://i.bytvi.com/domain_icons/localmatters.png',
      language: 'english',
      country: ['new zealand'],
      category: ['health'],
      ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
    },
    {
      article_id: '66a8e7cf31e1482df2fa18382e00a3ee',
      title:
        'Deliveroo rider transports food on penny farthing bicycle in west London',
      link: 'https://www.standard.co.uk/news/london/deliveroo-food-penny-farthing-bicycle-london-chelsea-b1158066.html',
      keywords: ['london', 'news'],
      creator: ['Daniel Keane'],
      video_url: null,
      description:
        'Delivery driver pictured using mode of transport popularised in 19th Century',
      content: 'ONLY AVAILABLE IN PAID PLANS',
      pubDate: '2024-05-15 19:58:53',
      image_url:
        'https://static.standard.co.uk/2024/04/18/08/dc88935ac879fde26de623a09a1036a6Y29udGVudHNlYXJjaGFwaSwxNzEzNTEwMjQw-2.75654254.jpg?width=1200&auto=webp',
      source_id: 'standarduk',
      source_priority: 2356,
      source_url: 'https://www.standard.co.uk',
      source_icon: 'https://i.bytvi.com/domain_icons/standarduk.png',
      language: 'english',
      country: ['united kingdom'],
      category: ['top'],
      ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
      ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
    },
  ],
  nextPage: '1715803133784262015',
};
