export const results = [
  {
    article_id: '16f5c56c3a299acf5f10b093aec39a9f',
    title: `Quand Blinken joue du Neil Young à Kiev en soutien à l'Ukraine`,
    link: 'http://www.lest-eclair.fr/id600069/article/2024-05-14/quand-blinken-joue-du-neil-young-kiev-en-soutien-lukraine',
    keywords: null,
    creator: ['Importer'],
    video_url: null,
    description: `Lecturezen On le sait amateur de guitare et de rock: le chef de la diplomatie américaine Antony Blinken a joué mardi soir "Rockin' in The Free World", de Neil Young`,
    content: '',
    pubDate: '2024-05-14 21:25:07',
    image_url:
      'https://remeng.rosselcdn.net/sites/all/themes/enabootstrap/images/placeholder.png',
    source_id: 'lesteclair',
    source_priority: 4117019,
    source_url: 'https://www.lest-eclair.fr',
    source_icon: 'https://i.bytvi.com/domain_icons/lesteclair.jpg',
    language: 'french',
    country: ['france'],
    category: ['top'],
    ai_tag: '',
    sentiment: '',
    sentiment_status: '',
    ai_region: '',
  },
  {
    article_id: 'faf1103de6a181ed62cdf478c6f506fc',
    title: 'Galeto Mamma Mia abre primeiro restaurante no Paraná',
    link: 'https://www.bemparana.com.br/publicacao/blogs/mesadividida/galeto-mamma-mia-abre-primeiro-restaurante-no-parana/',
    keywords: null,
    creator: ['Bárbara Magalhães Browne'],
    video_url: null,
    description:
      'O Galeto Mamma Mia, uma das mais tradicionais redes de gastronomia do Brasil, chega ao Paraná nesta terça-feira (14) com a inauguração de...O post Galeto Mamma Mia abre primeiro restaurante no Paraná apareceu primeiro em Bem Paraná.',
    content: 'ONLY AVAILABLE IN PAID PLANS',
    pubDate: '2024-05-14 21:21:00',
    image_url:
      'https://www.bemparana.com.br/wp-content/uploads/2024/05/Galeto-Mamma-Mia-Credito-Jony-Partos-1.jpg',
    source_id: 'bemparana_br',
    source_priority: 2047682,
    source_url: 'https://www.bemparana.com.br',
    source_icon: 'https://i.bytvi.com/domain_icons/bemparana_br.png',
    language: 'portuguese',
    country: ['brazil'],
    category: ['other'],
    ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
  },
  {
    article_id: '168b4a90e33a23f02e2fca33ab554879',
    title:
      "More than a third of children's restaurant meals still exceed salt target",
    link: 'https://news.knowledia.com/US/en/articles/more-than-a-third-of-children-s-restaurant-meals-still-exceed-salt-target-a32b970af3689117d94b74350efb043cf7fd573d?source=rss',
    keywords: null,
    creator: null,
    video_url: null,
    description:
      "Gourmet Burger Kitchen, Prezzo and Wetherspoon's among worst offenders, Action on Salt survey suggests - www.theguardian.com",
    content: 'ONLY AVAILABLE IN PAID PLANS',
    pubDate: '2024-05-14 21:16:14',
    image_url:
      'https://i.guim.co.uk/img/media/a95740ea97dfa7f0920890bf03d7ca958ea289b0/0_64_2904_1743/master/2904.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=79ebe10c703c7716aa70e1d6ebd8f194',
    source_id: 'knowledia',
    source_priority: 167779,
    source_url: 'http://news.knowledia.com',
    source_icon: 'https://i.bytvi.com/domain_icons/knowledia.png',
    language: 'english',
    country: ['united states of america'],
    category: ['top'],
    ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
  },
  {
    article_id: '29c10f2dd068b9c50fb85a8f776417de',
    title:
      "More than a third of children's restaurant meals still exceed salt target",
    link: 'https://news.knowledia.com/all/all/articles/more-than-a-third-of-children-s-restaurant-meals-still-exceed-salt-target-a32b970af3689117d94b74350efb043cf7fd573d?source=rss',
    keywords: null,
    creator: null,
    video_url: null,
    description:
      "Gourmet Burger Kitchen, Prezzo and Wetherspoon's among worst offenders, Action on Salt survey suggests - www.theguardian.com",
    content: 'ONLY AVAILABLE IN PAID PLANS',
    pubDate: '2024-05-14 21:16:14',
    image_url:
      'https://i.guim.co.uk/img/media/a95740ea97dfa7f0920890bf03d7ca958ea289b0/0_64_2904_1743/master/2904.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=79ebe10c703c7716aa70e1d6ebd8f194',
    source_id: 'knowledia',
    source_priority: 167779,
    source_url: 'http://news.knowledia.com',
    source_icon: 'https://i.bytvi.com/domain_icons/knowledia.png',
    language: 'english',
    country: ['india'],
    category: ['top'],
    ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
  },
  {
    article_id: 'd2b17e300b9c7d8551bb2b927d7e8d46',
    title: 'Stardew Valley gift guide: the best gifts for every villager',
    link: 'https://www.digitaltrends.com/gaming/stardew-valley-gift-guide/',
    keywords: [
      'gaming',
      'guides',
      'best gifts',
      'farming simulator',
      'game guide',
      'gift guide',
      'stardew valley',
    ],
    creator: ['Jesse Lennox'],
    video_url: null,
    description:
      "There's an art to giving gifts in Stardew Valley just like there is to farming. Each NPC likes different things, but it can be hard to learn what without help.",
    content: 'ONLY AVAILABLE IN PAID PLANS',
    pubDate: '2024-05-14 21:15:57',
    image_url:
      'https://www.digitaltrends.com/wp-content/uploads/2018/02/Stardew-Valley.jpg?resize=440%2C292&p=1',
    source_id: 'digitaltrends',
    source_priority: 287,
    source_url: 'https://www.digitaltrends.com',
    source_icon: 'https://i.bytvi.com/domain_icons/digitaltrends.png',
    language: 'english',
    country: ['united states of america'],
    category: ['technology'],
    ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
  },
  {
    article_id: '767875d897ac7d894f1ab0eaf13b74c5',
    title: 'Llega Uber Eats a tres ciudades más del estado de Chihuahua',
    link: 'https://www.elheraldodechihuahua.com.mx/local/chihuahua/llega-uber-eats-a-tres-ciudades-mas-del-estado-de-chihuahua-11917475.html',
    keywords: ['chihuahua'],
    creator: null,
    video_url: null,
    description:
      'Son más de mil comercios registrados en la Capital y Juárez, y la expectativa es sumar 250 establecimientos en 2024 con las otras urbes',
    content: 'ONLY AVAILABLE IN PAID PLANS',
    pubDate: '2024-05-14 21:10:50',
    image_url: null,
    source_id: 'elheraldodechihuahua',
    source_priority: 94227,
    source_url: 'https://www.elheraldodechihuahua.com.mx',
    source_icon: 'https://i.bytvi.com/domain_icons/elheraldodechihuahua.png',
    language: 'spanish',
    country: ['mexico'],
    category: ['top'],
    ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
  },
  {
    article_id: '089b5d4a7dd50ae293a85561703848d8',
    title: '"Gute Nacht!", Tag der Artenvielfalt',
    link: 'https://www.meinbezirk.at/floridsdorf/c-regionauten-community/gute-nacht-tag-der-artenvielfalt_a6692819',
    keywords: ['regionauten-community'],
    creator: ['Verein Natur im Garten Wien'],
    video_url: null,
    description:
      'Am 22. Mai, dem Internationalen Tag der Artenvielfalt, wird daran erinnert, dass der Schutz von Arten, Lebensräumen und genetischer Vielfalt weltweit unser aller Bemühen braucht. Dabei ist es wichtig zu bedenken, dass nicht nur Organismen schutzbedürftig sind, die wir tagsüber wahrnehmen können. Die Nacht wird von zahlreichen Arten belebt, die den meisten von uns, während wir schlafen, verborgen bleiben. Laternen, Gebäudebeleuchtung oder Licht von Schaufenstern und Reklame machen die Nacht im...',
    content: 'ONLY AVAILABLE IN PAID PLANS',
    pubDate: '2024-05-14 21:07:56',
    image_url:
      'https://media04.meinbezirk.at/article/2024/05/14/7/39798047_L.jpg',
    source_id: 'meinbezirk',
    source_priority: 2240706,
    source_url: 'https://www.meinbezirk.at',
    source_icon: 'https://i.bytvi.com/domain_icons/meinbezirk.png',
    language: 'german',
    country: ['austria'],
    category: ['top'],
    ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
    ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
  },
];
